# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-20 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainSettings',
            fields=[
                ('id_MainSettings', models.AutoField(primary_key=True, serialize=False)),
                ('user_login', models.CharField(max_length=50, null=True, unique=True)),
                ('user_password', models.CharField(max_length=50, null=True)),
                ('datetime', models.DateTimeField(null=True)),
                ('sync_time', models.BooleanField()),
                ('sync_server', models.URLField(null=True)),
                ('period', models.IntegerField(null=True)),
                ('remote_server', models.URLField(null=True)),
            ],
        ),
    ]
